<?php
/**
 * ChannelmanagerChannelStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\ChannelManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeminiCommerce\ChannelManager\Model;
use \GeminiCommerce\ChannelManager\ObjectSerializer;

/**
 * ChannelmanagerChannelStatus Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\ChannelManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChannelmanagerChannelStatus
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'CH_STATUS_UNKNOWN';

    public const ACTIVE = 'CH_STATUS_ACTIVE';

    public const DISABLED = 'CH_STATUS_DISABLED';

    public const UNDER_MAINTENANCE = 'CH_STATUS_UNDER_MAINTENANCE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::ACTIVE,
            self::DISABLED,
            self::UNDER_MAINTENANCE
        ];
    }
}


