<?php
/**
 * ChannelManagerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\ChannelManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Channel Manager Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\ChannelManager\Test\Api;

use \GeminiCommerce\ChannelManager\Configuration;
use \GeminiCommerce\ChannelManager\ApiException;
use \GeminiCommerce\ChannelManager\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ChannelManagerApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\ChannelManager
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChannelManagerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for channelManagerCreateAssociation
     *
     * CreateAssociation.
     *
     */
    public function testChannelManagerCreateAssociation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerCreateChannel
     *
     * CreateChannel.
     *
     */
    public function testChannelManagerCreateChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerCreateMarket
     *
     * CreateMarket.
     *
     */
    public function testChannelManagerCreateMarket()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerDeleteAssociation
     *
     * DeleteAssociation.
     *
     */
    public function testChannelManagerDeleteAssociation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerDeleteChannel
     *
     * DeleteChannel.
     *
     */
    public function testChannelManagerDeleteChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerDeleteMarket
     *
     * DeleteMarket.
     *
     */
    public function testChannelManagerDeleteMarket()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerGetChannel
     *
     * GetChannel.
     *
     */
    public function testChannelManagerGetChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerGetChannelWithAssociations
     *
     * GetChannelWithAssociations.
     *
     */
    public function testChannelManagerGetChannelWithAssociations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerGetMarket
     *
     * GetMarket.
     *
     */
    public function testChannelManagerGetMarket()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerGetMarketWithAssociations
     *
     * GetMarketWithAssociations.
     *
     */
    public function testChannelManagerGetMarketWithAssociations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerListChannels
     *
     * ListChannels.
     *
     */
    public function testChannelManagerListChannels()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerListChannelsWithAssociations
     *
     * ListChannelsWithAssociations.
     *
     */
    public function testChannelManagerListChannelsWithAssociations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerListMarkets
     *
     * ListMarkets.
     *
     */
    public function testChannelManagerListMarkets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerListMarketsWithAssociations
     *
     * ListMarketsWithAssociations.
     *
     */
    public function testChannelManagerListMarketsWithAssociations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerUpdateChannel
     *
     * UpdateChannel.
     *
     */
    public function testChannelManagerUpdateChannel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelManagerUpdateMarket
     *
     * UpdateMarket.
     *
     */
    public function testChannelManagerUpdateMarket()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
